name: Terraform VPC Deployment

on:
   workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Deploy VPC to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.3"
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}  # API_TOKEN for HCP Terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # ARN of the IAM role to assume
          aws-region: ${{ secrets.AWS_REGION }}         # AWS region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
