name: Terraform VPC Deployment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Deploy VPC to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # Updated to v3
        with:
          terraform_version: "1.10.3"
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}  # API_TOKEN for HCP Terraform

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true  # Allows pipeline to continue if changes are detected

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
